version: '3.7'

services:
  frontend:
    build: ./contact_management_front
    restart: always
    ports:
      - 80:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./contact_management_front:/src
      - /src/node_modules